export const LIST_CONVERSATION = "LIST_CONVERSATION";
export const FETCH_CONTACT = "FETCH_CONTACT";
export const FETCH_CONFIG = "FETCH_CONFIG";
export const PATIENT_PROFILE = "PATIENT_PROFILE";
export const DISCHARGE_DETAILS = "DISCHARGE_DETAILS";
export const REGISTER_API = "REGISTER_API";
