export const global = {
  PREVIOUSSCREEN: null,
  ACCESS_TOKEN: null,
  FCM_TOKEN: null,
  LOGIN_ACCESS_TOKEN: null,
  OWNER_EMAILID: null,
  OWNER_USERID: null,
  ISPREVIOUSTOCAPPROVED: false,
  TWILIOCLIENT: null,
  ISFIRSTTIMELOGGED: false,
  ISREFRESHTOKENCALLED: false,
  ISPENDINGAPPROVAL: false,
  ISLOCALBUILD: null as any,
};
